name: flood-prediction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pandas=1.4.3
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - scikit-learn=1.1.1
  - jupyter=1.0.0
  - notebook=6.4.12
  - ipykernel=6.15.1
  - ipywidgets=7.7.1
  - tqdm=4.64.0
  - pyyaml=6.0
  - requests=2.28.1
  - transformers=4.20.1
  - sentinelhub=3.4.0
  - rasterio=1.2.10
  - geopandas=0.10.2
  - folium=0.12.1
  - plotly=5.9.0
  - dash=2.5.1
  - pip
  - pip:
    - pystac-client==0.4.0
    - simplekml==1.3.6
    - pyproj==3.3.1